### ISSUE TITLE
How to make the extact.py download the mp4?

### ISSUE THREAD

**Issue by astandarduser** [XiyaoWong/spiders#13]
Sorry I am a little confused, when I run the extract.py, it lists all the mp4's but does not download, how to make it download like this?   https://camo.githubusercontent.com/f9dc47c16f860c6b311fcf4cbf71e8f89621595c/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f786979616f776f6e672f737069646572732f73637265656e73686f742f72756e2e676966

**Comment by xiyaowong** [comment]
It should be downloaded automatically by default. Have you installed all the required libraries?💭

**Comment by astandarduser** [comment]
I have these

# extractor
requests
pycryptodome

# extract
prettytable
click


everything seems to be working fine, just doesn't download

**Comment by astandarduser** [comment]
I must sleep now, will check tomorrow, thank you once again for your help   :)

**Comment by xiyaowong** [comment]
please send the screenshot

**Comment by astandarduser** [comment]
It seems to be an issue with the kuaishou script, for example, the douyin one downloads 
<img width="900" alt="kouishou" src="https://user-images.githubusercontent.com/23148457/82716306-f088d100-9cea-11ea-8256-f6ede7379e61.PNG">
