### ISSUE TITLE
kuaishou

### ISSUE THREAD

**Issue by astandarduser** [XiyaoWong/spiders#14]
I seems your fix that allows downloads for kuaishou has broken the desktop links again, the same error 'title': '快手，记录世界记录你'

**Comment by xiyaowong** [comment]
Oh~ It seems to be a hard work to consider all situations😣

**Comment by astandarduser** [comment]
It's ok, I think it might be an issue from my end or kuaishou altered something, I will report back here if I figure out

**Comment by astandarduser** [comment]
I confirmed it's my end that it's not working, not really an issue
