### ISSUE TITLE
bilibili 高清mp4

### ISSUE THREAD

**Issue by 5wcx** [XiyaoWong/spiders#17]
想要bilibili 1080 的原生mp4 接口。

**Comment by xiyaowong** [comment]
1080p需要登录。如果要弄只能单开一个项目。然而其实有很多好用的项目啦

**Comment by 5wcx** [comment]
https://www.xbeibeix.com/bilibili2/  这个项目有高清的mp4。要不你告诉我接口原理 我研究研究呢

**Comment by hypnotists** [comment]
新学python ,请问下载代码后如何编译运行，运行哪个文件，感谢！

**Comment by XiyaoWong** [comment]
> 新学python ,请问下载代码后如何编译运行，运行哪个文件，感谢！
README

**Comment by xiyaowong** [comment]
> 新学python ,请问下载代码后如何编译运行，运行哪个文件，感谢！

README

**Comment by incubus-ohy** [comment]
> https://www.xbeibeix.com/bilibili2/ 这个项目有高清的mp4。要不你告诉我接口原理 我研究研究呢
手机端搜索vid  然后可以拿到音频分离的非会员 的所有文件  ，然后用ffmeg合并

**Comment by incubus-ohy** [comment]
> 想要bilibili 1080 的原生mp4 接口。

需要登录  他没有原生的mp4接口    只能拿到音频分离文件
