### ISSUE TITLE
抖音不能用了 返回的链接 没东西

### ISSUE THREAD

**Issue by tdouguo** [XiyaoWong/spiders#20]
蓬佩奥“双标”！呼吁中方释放加拿大嫌犯，赵立坚：有何颜面资格@主持人 崔小花 https://v.douyin.com/J8B76ts/ 复制此链接，打开【抖音短视频】，直接观看视频！

**Comment by tdouguo** [comment]
https://aweme.snssdk.com/aweme/v1/play/?video_id=v0300f6a0000bh103h1u9o8khl6s6u20&ratio=720p&line=0   这是返回的链接 什么都没有

**Comment by xiyaowong** [comment]
一直是这样。浏览器改成手机头就行了。你可以用手机访问试试
