### ISSUE TITLE
大神你好  acfun的你的接口是m3u的可以增加mp4的吗？

### ISSUE THREAD

**Issue by 5wcx** [XiyaoWong/spiders#3]
我最近见到过别人的程序 这种链接可以抓到mp4地址。不知道接口是什么 ，你能搞出来吗？
链接地址是这样的： http://tx-safety-video.acfun.cn/mediacloud/acfun/acfun_video/_HqzwHV5zsUv5ikORMxxnCZ57jFEfr7yVZTsBkPY4IUoV9z7OHXzsWDBNN347awq.mp4?pkey=AAKf7uEXJLRQHesoGMG9YV0Lyj9zf45yhew8thKGBd3S8-SKGrykotFZE2SutIIytSib9pHPici_CWfopvgbKpc03Qj7IwAaN07B_eDm5JK2fOS4tN4dPqCWSqsSnLTRXilI4glJSuvwerGbtNZugdNWnwJRLpJp1wTIUDcikvT3cobxOuVBarRXjyBUj2HqQuIpSJ1HqVCl9TOYBtc5Hy9cNtyuv8A9ufeK4NfVbpGGWK-FYDiHgocQYAFI5VRSacZaqTP5vBT58CxLzQIz4bggpOPR8lQHnZLrUg4N8x6MMQ

**Comment by xiyaowong** [comment]
这个可能是抓包的APP接口，web端我的确找不到MP4的数据接口（可能是我遗漏了地方）:sweat_smile:。你可以自己尝试抓下包。然后方便发一下你所用的程序吗

**Comment by XiyaoWong** [comment]
😔
