### ISSUE TITLE
很棒，给个赞

### ISSUE THREAD

**Issue by yangfeng1994** [XiyaoWong/spiders#4]
我有个邪恶的想法，把这个库的python代码移植到android中，直接用安卓手机直接就能使用。博主支持不？

**Comment by xiyaowong** [comment]
你可以用这个在服务器搭解析接口，或者同样的原理用其他支持移动端的语言写一份
---原始邮件---
发件人:"yangfeng1994"<notifications@github.com>
发送时间:2020年4月20日 星期一 上午11:47
收件人:"XiyaoWong/spiders"<spiders@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:[XiyaoWong/spiders] 很棒，给个赞 (#4)



我有个邪恶的想法，把这个库的python代码移植到android中，直接用安卓手机直接就能使用。博主支持不？

&mdash;

**Comment by yangfeng1994** [comment]
可以。刚刚试了一下QQ音乐下载的，失败了。

**Comment by xiyaowong** [comment]
刚刚测试了，没问题呀
