### ISSUE TITLE
抖音的失败了

### ISSUE THREAD

**Issue by snltty** [XiyaoWong/spiders#6]

**Comment by xiyaowong** [comment]
你是用的release吗

**Comment by snltty** [comment]
clone master  下来 运行的

**Comment by xiyaowong** [comment]
我刚刚试了没问题呀，你发一下截图，好像不能发图，直接发错误信息

**Comment by snltty** [comment]
![1](https://user-images.githubusercontent.com/10977033/80588609-3d122100-8a4b-11ea-9b5d-959a3a88538a.png)
![2](https://user-images.githubusercontent.com/10977033/80588620-400d1180-8a4b-11ea-9dee-f7d73a65f99f.png)

**Comment by snltty** [comment]
https://v.douyin.com/wxndV5/

**Comment by xiyaowong** [comment]
:smile: 这个只能解析单个视频

**Comment by snltty** [comment]
那好的吧

**Comment by snltty** [comment]
哔哩哔哩的怎么下载来着，没有找到 解析代码里的那种 av 的格式链接
